import { drizzle } from "drizzle-orm/mysql2";
import {
  InsertUser,
  users,
  manufacturers,
  products,
  competitorProducts,
  tenders,
  tenderItems,
  tenderResults,
  inventory,
  inventoryMovements,
  documents,
  tasks,
  timesheetEntries,
  customers,
  forecasts,
  deliveries,
  deliveryItems,
  invoices,
  invoiceItems,
  expenses,
  chatConversations,
  chatMessages,
  InsertManufacturer,
  InsertProduct,
  InsertTender,
  InsertTenderItem,
  InsertTenderResult,
  InsertInventory,
  InsertInventoryMovement,
  InsertDocument,
  InsertTask,
  InsertTimesheetEntry,
  InsertCustomer,
  InsertForecast,
  InsertDelivery,
  InsertDeliveryItem,
  InsertInvoice,
  InsertInvoiceItem,
  InsertExpense,
  InsertChatConversation,
  InsertChatMessage,
} from "../drizzle/schema";
import { ENV } from "./_core/env";
import { LIMITS } from "@shared/const";

// Pagination options type
export type PaginationOptions = {